import Head from 'next/head'
import Image from 'next/image'
import Feedback from '../components/Feedback/Feedback'
import Footer from '../components/Footer/Footer'
import Header from '../components/Header/Header'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import AdminPanel from '../components/AdminPanel/AdminPanel'

export default function Home({products}) {

  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>

      </Header>

          <AdminPanel products={products}>

          </AdminPanel>
       
      {/* feedback */}



      <Footer>

      </Footer>


    </div>
  )
}
export async function getServerSideProps(context) {
  const response = await fetch("http://localhost:3000/localDB/MOCK_DATA.json" );
  const products = await response.json();

  return{
      props:{
           products,
      },
  }

}
