import Head from 'next/head'
import Image from 'next/image'
import Feedback from '../components/Feedback/Feedback'
import Footer from '../components/Footer/Footer'
import Header from '../components/Header/Header'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>

      </Header>
      {/* feedback */}
      <Feedback>

      </Feedback>



      <Footer>

      </Footer>


    </div>
  )
}
