import Head from 'next/head'
import Image from 'next/image'
import Feedback from '../components/Feedback/Feedback'
import Footer from '../components/Footer/Footer'
import Header from '../components/Header/Header'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import AdminPanel from '../components/AdminPanel/AdminPanel'
import AdminPanel2 from '../components/AdminPanel/AdminPanel2'

export default function Home({products}) {

  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>

      </Header>
       
      {/* MainSite */}



      <Footer>

      </Footer>


    </div>
  )
}

