const CompanyInfo = {
  Contact: [
    {
      Miasto: "Wroclaw",
      Panstwo: "Polska",
      Telefon: "+4800000000",
      Ulica: "Taminowa",
      Numer: "99",
      Czynne: [
        {
          id: 0,
          Group: "pn-pt",
          Day: "Poniedzialek",
          od: "8",
          do: "22",
        },
        {
          id: 1,
          Group: "pn-pt",
          Day: "Wtorek",
          od: "8",
          do: "22",
        },
        {
          id: 2,
          Group: "pn-pt",
          Day: "Sroda",
          od: "8",
          do: "22",
        },
        {
          id: 3,
          Group: "pn-pt",
          Day: "Czwartek",
          od: "8",
          do: "22",
        },
        {
          id: 4,
          Group: "pn-pt",
          Day: "Piatek",
          od: "8",
          do: "22",
        },
        {
          id: 5,
          Group: "sb-nd",
          Day: "Sobota",
          od: "12",
          do: "20",
        },
        {
          id: 6,
          Group: "sb-nd",
          Day: "Niedziela",
          od: "1",
          do: "1",
        },
      ],
    },

    {
      Miasto: "Xdonbas",
      Panstwo: "Ukraina",
      Telefon: "+3200000000",
      Ulica: "Mariu",
      Numer: "22",
      Czynne: [
        {
          id: 0,
          Group: "pn-pt",
          Day: "Poniedzialek",
          od: "8",
          do: "22",
        },
        {
          id: 1,
          Group: "pn-pt",
          Day: "Wtorek",
          od: "8",
          do: "22",
        },
        {
          id: 2,
          Group: "pn-pt",
          Day: "Sroda",
          od: "8",
          do: "22",
        },
        {
          id: 3,
          Group: "pn-pt",
          Day: "Czwartek",
          od: "8",
          do: "22",
        },
        {
          id: 4,
          Group: "pn-pt",
          Day: "Piatek",
          od: "8",
          do: "22",
        },
        {
          id: 5,
          Group: "sb-nd",
          Day: "Sobota",
          od: "10",
          do: "20",
        },
        {
          id: 6,
          Group: "sb-nd",
          Day: "Niedziela",
          od: "1",
          do: "1",
        },
      ],
    },
  ],
};
export default CompanyInfo;
