export const shoeCategory = [
  "Football",
  "Tennis",
  "Basketball",
  "Running",
  "Skateboarding",
  "Soccer",
  "Golf",
  "Baseball",
  "Hiking",
  "Cycling",
  "Training",
  "Walking",
  "Lifestyle",
  "Yoga",
  "Gym",
  "Boxing",
  "Volleyball",
  "Dance",
  "Tennis",
  "Skateboarding",
  "Soccer",
  "Golf",
  "Baseball",
  "Hiking",
  "Cycling",
  "Training",
  "Walking",
  "Lifestyle",
  "Yoga",
  "Gym",
  "Boxing",
  "Volleyball",
  "Dance",
];
export const shoeType = [
  "Sandals",
  "Slippers",
  "Boots",
  "Sneakers",
  "Loafers",
  "Flats",
  "Heels",
  "Wedges",
  "Clogs",
  "Mules",
  "Slip-ons",
  "Espadrilles",
  "Oxfords",
  "Derbys",
  "Monks",
  "Brogues",
  "Loafers",
  "Flats",
  "Heels",
  "Wedges",
  "Clogs",
  "Mules",
  "Slip-ons",
  "Espadrilles",
  "Oxfords",
  ,
  "Monks",
  "Brogues",
];

export const shoeSize = [
  { value: "34", label: "34" },
  { value: "35", label: "35" },
  { value: "36", label: "36" },
  { value: "37", label: "37" },
  { value: "38", label: "38" },
  { value: "39", label: "39" },
  { value: "40", label: "40" },
  { value: "41", label: "41" },
  { value: "42", label: "42" },
  { value: "43", label: "43" },
  { value: "44", label: "44" },
  { value: "45", label: "45" },
  { value: "46", label: "46" },
];
